build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-python:3.11-bookworm
  amd64: ghcr.io/home-assistant/amd64-base-python:3.11-bookworm

# Set build arguments
args:
  MATTER_SERVER_VERSION: 7.0.1
