name: Schnell Matter Controller
version: "1.0.0"
slug: matter_controller
description: Custom Matter controller with commissioning support for external apps
url: "https://github.com/schnellenergy/ha-matter-addon"
arch:
  - aarch64
  - amd64
discovery:
  - matter
hassio_api: true
homeassistant: 2024.6.0
host_dbus: true
host_network: true
startup: services
stage: stable
init: false
ports:
  8099/tcp: 8099
  5580/tcp: null
ports_description:
  8099/tcp: Matter Controller API
  5580/tcp: Matter Server (internal)
map:
  - share:rw
options:
  log_level: info
  token_lifetime_days: 30
  allow_external_commissioning: true
  analytics_enabled: true
  max_log_entries: 1000
  max_analytics_events: 1000
  auto_register_with_ha: true
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  token_lifetime_days: int(1,365)
  allow_external_commissioning: bool
  analytics_enabled: bool
  max_log_entries: int(100,10000)
  max_analytics_events: int(100,10000)
  auto_register_with_ha: bool
webui: "http://[HOST]:[PORT:8099]"
ingress: true
ingress_port: 8099
panel_icon: mdi:chip
