name: Matter Controller
version: "1.0.0"
slug: matter_controller
description: Matter controller for Home Assistant
arch:
  - aarch64
  - amd64
startup: application
init: false
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
