name: Matter Controller
version: "1.0.0"
slug: matter_controller
description: Custom Matter controller with commissioning support for external apps
url: "https://github.com/schnellenergy/ha-matter-addon"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Matter Controller API
map:
  - share:rw
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
webui: "http://[HOST]:[PORT:8099]"
