name: Matter Controller
version: "1.0.0"
slug: matter_controller
description: Matter controller for Home Assistant
url: "https://github.com/schnellenergy/ha-matter-addon"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
init: false
map:
  - share:rw
options:
  log_level: info
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
