name: CHIP Tool API
version: "1.0.0"
slug: chip_tool_api
description: Expose Matter chip-tool via HTTP API new
startup: application
boot: auto
init: false
host_network: true
ports:
  6000/tcp: 6000
homeassistant: 2023.0.0
arch:
  - amd64
  - aarch64
  - armv7
options: {}
schema: {}
